name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
 
    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: set JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        working-directory: demo/
        run: chmod +x gradlew

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      - name: Show Current Time
        run: echo "CurrnetTime=$"
        shell: bash

      - name: Build with Gradle
        working-directory: demo/
        run: ./gradlew clean build -Dspring.profiles.active=prod -x test  # build with Gradle, excluding tests
        shell: bash

      - name: Generate deployment package
        working-directory: demo/
        run: |
          mkdir -p deploy
          cp build/libs/*.jar deploy/application.jar
          cp Procfile deploy/Procfile
          cp -r .ebextensions deploy/.ebextensions
          cp -r .platform deploy/.platform
          cd deploy && zip -r deploy.zip .


      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{secrets.AWS_ACCESS_KEY}}
          aws_secret_key: ${{secrets.AWS_SECRET_KEY}}
          application_name: dears-core-server
          environment_name: Dears-core-server-env
          version_label: github-action-${{ steps.current-time.outputs.formattedTime }} 
          region: ap-northeast-2
          deployment_package: demo/deploy/deploy.zip
          wait_for_environment_recovery: 180
