name: CI

on:
  pull_request: # Perform CD during PR
    branches: 
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      checks: write
      pull-requests: write
      contents: read

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Set up Temurin 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: grant permission to gradle
        run: chmod +x ./gradlew

      - name: run test
        run: ./gradlew --info test
        
      - name: Build and Test with Gradle
        run: ./gradlew build --no-daemon

      - name: Upload Test Result
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Test Result
          path: build/reports/tests/test

      - name: Publish result of unit test
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: "**/build/test-results/test/TEST-*.xml"
          github_token: ${{ github.token }}
          
      - name: Publish failure of unit test
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          github_token: ${{ github.token }}
